branch-defaults:
  default:
    environment: null
    group_suffix: null
  deploy:
    artifact: runnable.jar
global:
  application_name: springboot-migration-elasticbeanstalk
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
