name: All YouTube French videos workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest French videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 500
          readme_path: './videos/README.md'
          comment_tag_name: "FRENCH-YOUTUBE-VIDEOS"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCDQY4e8xNx7zYag0vl9TWfg"
